#!/bin/bash

source ~/.bashrc
export PATH=$PATH:/workspaces/runCommand

clear
BAT_PATH="/sys/class/power_supply/BAT0"
WARNING_FOUND=false

# --- 2. Check for Danger ---
if [ -d "$BAT_PATH" ]; then
    CAP=$(cat "$BAT_PATH/capacity")
    STAT=$(cat "$BAT_PATH/status")

    # If battery is low and discharging, set the warning
    if [ "$STAT" = "Discharging" ]; then
        echo "!!! WARNING: DISCHARGING BATTERY ($CAP%) !!!"
        WARNING_FOUND=true
    fi
fi




# --- 3. The Logic ---
# Only show the time if NO warning was triggered
if [ "$WARNING_FOUND" = false ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S')"
fi

read -e -p " > " cmd

if [ -n "$cmd" ]; then
    # nohup $cmd >/dev/null 2>&1 &
    # i3-msg exec "$cmd"
    setsid $cmd >/dev/null 2>&1 &

    sleep 0.1
fi
