#!/bin/bash
set -e

BIN_PATH="/home/daos/.software/newsReader"
REMOTE_URL="https://raw.githubusercontent.com/daosparty/single-apps/refs/heads/master/newsReader"

mkdir -p "$(dirname "$BIN_PATH")"

if [ ! -f "$BIN_PATH" ]; then
    echo "Binary not found. Downloading..."

    curl -fsSL "$REMOTE_URL" -o "$BIN_PATH"

    chmod +x "$BIN_PATH"
fi

exec "$BIN_PATH"
